### ISSUE TITLE
This plugin uses the `unique` function which does not exist pre Bolt 3.1

### ISSUE THREAD

**Issue by dantleech** [graham73may/bolt-taxonomylist-field#1]
The `unique` function does not exist in vanilla twig: https://github.com/graham73may/bolt-taxonomylist-field/blob/master/templates/bolt/_taxonomylist.twig#L57

**Comment by graham73may** [comment]
This is a plugin for Bolt CMS. It must be one of the custom twig functions that's been added as part of the Bolt core.

**Comment by dantleech** [comment]
Looks like it was introduced in Bolt 3.1, doesn't exist in 3.0. *Maybe* its worth bumping the deps.

**Comment by graham73may** [comment]
Ah I see! I've bumped the dependency to 3.1 in the composer.json. Didn't realise unique was so new to Bolt! Thanks.

**Comment by dantleech** [comment]
Thanks :)

On 30 December 2016 18:46:23 GMT+00:00, graham73may <notifications@github.com> wrote:
>Ah I see! I've bumped the dependency to 3.1 in the composer.json.
>Didn't realise unique was so new to Bolt! Thanks. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/graham73may/bolt-taxonomylist-field/issues/1#issuecomment-269807345

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
